# Generated by Django 4.1.7 on 2023-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headerPagePicture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profilPicture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
